#pragma once

typedef enum _HV_MUTATION_TYPE
{
	NONE = 0,
	INCREMENTING_SINGLE = 1,
	BIT_FLIPPING_SINGLE = 2,
	SPECIAL_VALUE_SINGLE = 3,
	INCREMENTING_MULTIPLE = 4,
	BIT_FLIPPING_MULTIPLE = 5,
	SPECIAL_VALUE_MULTIPLE = 6
} HV_MUTATION_TYPE;